In [47]:
import math
import numpy as np

aX = np.array([[[0.1, 0.2, 0.3], [0.0, 0.0, -1.0]], [[0.7, 0.8, -0.9], [1.0, 1.1, -1.2]], [[1,2,3],[4,5,6]]])
print(aX)
print(aX.shape)


[[[ 0.1  0.2  0.3]
  [ 0.   0.  -1. ]]

 [[ 0.7  0.8 -0.9]
  [ 1.   1.1 -1.2]]

 [[ 1.   2.   3. ]
  [ 4.   5.   6. ]]]
(3, 2, 3)


In [54]:
aX[:,:,0:2][:,:,::-1]

array([[[0.2, 0.1],
        [0. , 0. ]],

       [[0.8, 0.7],
        [1.1, 1. ]],

       [[2. , 1. ],
        [5. , 4. ]]])

In [46]:
aR = np.concatenate((aX[0,:,:], aX[-1,:,:], aX[1:-1, 0,:], aX[1:-1,-1,:]))
print(aR)


[[ 0.1  0.2  0.3]
 [ 0.   0.  -1. ]
 [ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 0.7  0.8 -0.9]
 [ 1.   1.1 -1.2]]


array([[0.1, 0.2],
       [0. , 0. ]])

In [17]:
aLen = np.expand_dims(np.linalg.norm(aX, axis=2), axis=2)
print(aLen)

aXn = aX / aLen
print(aXn)

print(np.linalg.norm(aXn, axis=2))

[[[0.37416574]
  [1.        ]]

 [[1.39283883]
  [1.91049732]]]
[[[ 0.26726124  0.53452248  0.80178373]
  [ 0.          0.         -1.        ]]

 [[ 0.50257071  0.57436653 -0.64616234]
  [ 0.52342392  0.57576631 -0.62810871]]]
[[1. 1.]
 [1. 1.]]


In [27]:
aY = aXn[:,:,0:2]
print(aY)
print("---")

aLen = np.linalg.norm(aY, axis=2)
print(aLen)
print("---")

aMask = aLen > 1e-6
print(aMask)
print("---")

aIdx = np.argwhere(aMask)
print(aIdx)
print("---")

aYn = np.divide(aY, np.expand_dims(aLen, axis=2), where=np.expand_dims(aMask, axis=2))
# aYn = aY / np.expand_dims(aLen, axis=2)
print(aYn)
print("---")


[[[0.26726124 0.53452248]
  [0.         0.        ]]

 [[0.50257071 0.57436653]
  [0.52342392 0.57576631]]]
---
[[0.5976143  0.        ]
 [0.76319999 0.7781256 ]]
---
[[ True False]
 [ True  True]]
---
[[0 0]
 [1 0]
 [1 1]]
---
[[[0.4472136  0.89442719]
  [0.         0.        ]]

 [[0.65850461 0.75257669]
  [0.67267279 0.73994007]]]
---


In [28]:
aZ = -aXn[:,:,2]
print(aZ)
print("---")

aA = np.arctan2(aLen, aZ)
print(np.degrees(aA))


[[-0.80178373  1.        ]
 [ 0.64616234  0.62810871]]
---
[[143.3007748    0.        ]
 [ 49.74712002  51.08927619]]
